from __future__ import annotations

import argparse
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DEFAULT_NM = PROJECT_ROOT / "toolchain" / "mingw-w64-x86_64-arm-none-eabi" / "bin" / "arm-none-eabi-nm.exe"
TARGET_SYMBOLS = ("__cflash_start", "__cflash_end")
SKIP_NAME_PREFIXES = (".", "$")
SKIP_NAME_EXACT: set[str] = set()


@dataclass(frozen=True)
class Symbol:
    name: str
    address: int
    symbol_type: str


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="ELF helper for cflash range lookup and symbol comparison.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    compare_parser = subparsers.add_parser(
        "compare",
        help="Compare cflash symbol addresses between a reference ELF and a candidate ELF.",
    )
    compare_parser.add_argument("reference_elf", type=Path, help="Reference ELF generated by the main build.")
    compare_parser.add_argument("candidate_elf", type=Path, help="Candidate ELF generated by chcm_config.")
    add_common_nm_argument(compare_parser)
    compare_parser.add_argument(
        "--detail",
        action="store_true",
        help="Print all compared cflash symbol addresses.",
    )

    range_parser = subparsers.add_parser(
        "cflash-range",
        help="Print __cflash_start and __cflash_end from an ELF.",
    )
    range_parser.add_argument("elf", type=Path, help="ELF file to inspect.")
    add_common_nm_argument(range_parser)

    return parser


def add_common_nm_argument(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--nm",
        type=Path,
        default=DEFAULT_NM,
        help=f"Path to arm-none-eabi-nm. Default: {DEFAULT_NM}",
    )


def run_nm(nm_path: Path, elf_path: Path) -> list[Symbol]:
    completed = subprocess.run(
        [str(nm_path), "-n", str(elf_path)],
        cwd=PROJECT_ROOT,
        check=True,
        text=True,
        capture_output=True,
    )
    symbols: list[Symbol] = []
    for line in completed.stdout.splitlines():
        match = re.match(r"^([0-9A-Fa-f]+)\s+([A-Za-z])\s+(.+)$", line.strip())
        if not match:
            continue
        address_text, symbol_type, name = match.groups()
        symbols.append(Symbol(name=name, address=int(address_text, 16), symbol_type=symbol_type))
    return symbols


def require_existing_file(path: Path, description: str) -> None:
    if not path.is_file():
        raise SystemExit(f"{description} not found: {path}")


def is_named_cflash_symbol(symbol: Symbol, start: int, end: int) -> bool:
    if not (start <= symbol.address < end):
        return False
    if symbol.name in SKIP_NAME_EXACT:
        return False
    if symbol.name.startswith(SKIP_NAME_PREFIXES):
        return False
    return True


def collect_cflash_symbols(symbols: list[Symbol], start: int, size: int) -> dict[str, Symbol]:
    end = start + size
    collected: dict[str, Symbol] = {}
    for symbol in symbols:
        if is_named_cflash_symbol(symbol, start, end):
            collected[symbol.name] = symbol
    return collected


def collect_named_symbols(symbols: list[Symbol], names: tuple[str, ...]) -> dict[str, Symbol]:
    collected: dict[str, Symbol] = {}
    for symbol in symbols:
        if symbol.name in names:
            collected[symbol.name] = symbol
    return collected


def get_cflash_range(symbols: list[Symbol]) -> tuple[int, int]:
    named_symbols = collect_named_symbols(symbols, TARGET_SYMBOLS)
    missing = [name for name in TARGET_SYMBOLS if name not in named_symbols]
    if missing:
        raise SystemExit(f"Missing symbols: {', '.join(missing)}")
    start = named_symbols["__cflash_start"].address
    end = named_symbols["__cflash_end"].address
    return start, end


def format_hex(value: int) -> str:
    return f"0x{value:08X}"


def print_detail(reference_symbols: dict[str, Symbol], candidate_symbols: dict[str, Symbol]) -> None:
    print("\ndetail:")
    for name in sorted(set(reference_symbols) | set(candidate_symbols)):
        reference_symbol = reference_symbols.get(name)
        candidate_symbol = candidate_symbols.get(name)
        if reference_symbol is None:
            status = "extra"
            reference_address = "-"
            candidate_address = format_hex(candidate_symbol.address)
        elif candidate_symbol is None:
            status = "missing"
            reference_address = format_hex(reference_symbol.address)
            candidate_address = "-"
        elif reference_symbol.address == candidate_symbol.address:
            status = "match"
            reference_address = format_hex(reference_symbol.address)
            candidate_address = format_hex(candidate_symbol.address)
        else:
            status = "mismatch"
            reference_address = format_hex(reference_symbol.address)
            candidate_address = format_hex(candidate_symbol.address)
        print(f"  {status:8} {name}: reference={reference_address} candidate={candidate_address}")


def compare_command(args: argparse.Namespace) -> int:
    require_existing_file(args.reference_elf, "Reference ELF")
    require_existing_file(args.candidate_elf, "Candidate ELF")
    require_existing_file(args.nm, "nm tool")

    reference_all_symbols = run_nm(args.nm, args.reference_elf)
    candidate_all_symbols = run_nm(args.nm, args.candidate_elf)
    reference_start, reference_end = get_cflash_range(reference_all_symbols)
    candidate_start, candidate_end = get_cflash_range(candidate_all_symbols)

    reference_symbols = collect_cflash_symbols(
        reference_all_symbols,
        reference_start,
        max(reference_end - reference_start, 0),
    )
    candidate_symbols = collect_cflash_symbols(
        candidate_all_symbols,
        candidate_start,
        max(candidate_end - candidate_start, 0),
    )
    reference_symbols["__cflash_start"] = Symbol("__cflash_start", reference_start, "R")
    reference_symbols["__cflash_end"] = Symbol("__cflash_end", reference_end, "R")
    candidate_symbols["__cflash_start"] = Symbol("__cflash_start", candidate_start, "R")
    candidate_symbols["__cflash_end"] = Symbol("__cflash_end", candidate_end, "R")

    reference_names = set(reference_symbols)
    candidate_names = set(candidate_symbols)
    missing_in_candidate = sorted(reference_names - candidate_names)
    extra_in_candidate = sorted(candidate_names - reference_names)

    mismatches: list[str] = []
    for name in sorted(reference_names & candidate_names):
        reference_symbol = reference_symbols[name]
        candidate_symbol = candidate_symbols[name]
        if reference_symbol.address != candidate_symbol.address:
            mismatches.append(
                f"{name}: reference={format_hex(reference_symbol.address)} "
                f"candidate={format_hex(candidate_symbol.address)}"
            )

    print(f"reference elf: {args.reference_elf}")
    print(f"candidate elf: {args.candidate_elf}")
    print(f"reference cflash range: {format_hex(reference_start)} - {format_hex(reference_end)}")
    print(f"candidate cflash range: {format_hex(candidate_start)} - {format_hex(candidate_end)}")
    print(f"reference symbols in cflash: {len(reference_symbols)}")
    print(f"candidate symbols in cflash: {len(candidate_symbols)}")
    if args.detail:
        print_detail(reference_symbols, candidate_symbols)

    if not missing_in_candidate and not extra_in_candidate and not mismatches:
        print("result: all cflash symbol addresses match")
        return 0

    print("result: differences found")

    if missing_in_candidate:
        print("\nmissing in candidate:")
        for name in missing_in_candidate:
            print(f"  {name} @ {format_hex(reference_symbols[name].address)}")

    if extra_in_candidate:
        print("\nextra in candidate:")
        for name in extra_in_candidate:
            print(f"  {name} @ {format_hex(candidate_symbols[name].address)}")

    if mismatches:
        print("\naddress mismatches:")
        for entry in mismatches:
            print(f"  {entry}")

    return 1


def cflash_range_command(args: argparse.Namespace) -> int:
    require_existing_file(args.elf, "ELF")
    require_existing_file(args.nm, "nm tool")

    start, end = get_cflash_range(run_nm(args.nm, args.elf))

    print(f"elf: {args.elf}")
    print(f"__cflash_start = {format_hex(start)}")
    print(f"__cflash_end   = {format_hex(end)}")
    print(f"size           = 0x{end - start:X} ({end - start} bytes)")
    return 0


def main() -> None:
    args = build_parser().parse_args()
    if args.command == "compare":
        raise SystemExit(compare_command(args))
    if args.command == "cflash-range":
        raise SystemExit(cflash_range_command(args))
    raise SystemExit(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    main()
